### ISSUE TITLE
Consider moving module to voxpupuli

### ISSUE THREAD

**Issue by sammcj** [puppetlabs/puppetlabs-node_encrypt#21]
node_encrypt seems to have gained a lot of traction recently and there's a number of organisations I've seen that now rely on it.

I wondered what your thoughts @binford2k would be on approaching @voxpupuli to see if they'd be interested in assisting with it's development?

Another option is to see if @puppet would consider supporting the module or it's functionality in core Puppet, but that would result in people having to log Jira tickets for problems etc... which is a bit annoying.

- https://voxpupuli.org

**Comment by binford2k** [comment]
I don't have a problem with the idea, but I don't know that they'd want to own responsibility for something that alters catalog internals. @bastelfreak was wondering if you'd be willing to maintain it?

My long term goal for this module has always been to get the functionality into the `Sensitive` type and then freeze this for older versions. For now, I'll see if I can allocate company time to work on this, maybe even get it into the test matrix.

**Comment by danielparks** [comment]
@binford2k is there a feature request ticket or something that's public in JIRA?

**Comment by binford2k** [comment]
Henrik is working on his own implementation. I can't tell if they're in design or still gathering requirements. There's a PR that's been open for a few months now. PUP-8971

**Comment by alexjfisher** [comment]
@binford2k That never happened.  Is migration something you'd still consider?

**Comment by binford2k** [comment]
Absolutely. The consensus last time was that there was a little concern about owning something that mucked with catalog internals, but I don't have any misgivings on my side. As soon as y'all want it, it's yours.
